project_name: protoeval
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm
      - '386'
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: amd64
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: amd64
      - goos: windows
        goarch: arm64
archives:
 -
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"


checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

universal_binaries:
-
  name_template: '{{.ProjectName}}'
  replace: true

dist: dist
